name: Build

permissions:
  contents: write

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # UPKEEP due: "2025-09-09" label: "GitHub actions checkout" interval: "+1 year"
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt install qemu-utils bzip2

      - name: Build
        run: sudo -E ./build-image.sh "alpine-virt-image-${{ github.ref_name }}"

      # UPKEEP due: "2025-09-09" label: "GitHub action softprops/action-gh-release" interval: "+1 year"
      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'alpine-virt-image-*.qcow2.bz2'
